### ISSUE TITLE
Resolve conflict with Simulink

### ISSUE THREAD

**Issue by ljardine** [mathworks/OpenTelemetry-Matlab#121]
Please can you resolve a blocking conflict with Simulink.

Steps:
Unpack attached zip (though essentially the same as either metrics example)
Open Docker, then in folder: docker-compose up -d

Open 23b & install toolbox 1.7.0.
Run myExample.m (or either metrics example) -> should be fine
Then open Simulink -> should throw error

Restart 23b
Open Simulink -> should be fine
The run myExample.m (or either metrics example) -> should throw error

[untitled1.zip](https://github.com/mathworks/OpenTelemetry-Matlab/files/15337052/untitled1.zip)

**Comment by duncanpo** [comment]
This seems to be caused by a conflict of different versions of abseil_dll.dll
