### ISSUE TITLE
Invalid synchronous instrument name with spaces 

### ISSUE THREAD

**Issue by ricktu-mw** [mathworks/OpenTelemetry-Matlab#28]
Create a synchronous instrument with a string containing spaces as input name will give an error in the cpp-opentelemetry end.
For example,
`counter = meter.createCounter("my counter");`

A temporary fix has been applied to replace spaces with underscores. But this issue may be further discussed.

**Comment by duncanpo** [comment]
We need a more general solution. Spaces are not the only character disallowed. See [sdk/src/metrics/instrument_metadata_validator.cc](https://github.com/open-telemetry/opentelemetry-cpp/blob/35a9362732216c00a24bdd4c98ebb5f9bbaab2c5/sdk/src/metrics/instrument_metadata_validator.cc) For names, it is only allowing letters, numbers, underscore, minus, dot, slash. All other symbols are disallowed. Units also have its own rules. 
Consider something simple such as if a name fails, just use an empty name

**Comment by duncanpo** [comment]
The current behavior is if instrument name invalid, the instrument will still be created with the invalid name. But no values will be recorded and the instrument becomes like a no-op instrument.
Also, the naming rules is part of the [OpenTelemetry spec](https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-name-syntax)

**Comment by duncanpo** [comment]
There is also this "error" message: [Error] File: otel-cpp\src\opentelemetry-cpp\sdk\src\metrics\meter.cc:67 Meter::CreateDoubleCounter - failed. Invalid parameters.__5352153afdsaf  . Measurements won't be recorded.

This seems to me perfectly reasonable. Although it's an error message, it doesn't stop anything, so is effectively a warning. And it exactly describe the no-op behavior. 

I think it is reasonable to just stick to the C++ behavior and not do anything extra, which means we should back out the change to convert empty spaces to underscore. Any invalid names will get the warning message and becomes a no-op instrument.

**Comment by duncanpo** [comment]
Backed out the previous change to replace spaces with underscores.
